CREATE TABLE FACT_ISSUE (
	ID INT (18) NOT NULL AUTO_INCREMENT,
	IDT INT (18) NOT NULL,
	ASSIGNEE INT (18) NOT NULL,
	KIND INT (18) NOT NULL,
	STATUS INT (18) NOT NULL,
	PROJECT INT (18) NOT NULL,
	CREATED INT (18) NOT NULL,
	PRIMARY KEY (ID)
	);